// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbZklnlSH19nPegOT1zopZhtZC3QOMwo',
    appId: '1:482587259419:web:41b9a697fc586fb6f73ebe',
    messagingSenderId: '482587259419',
    projectId: 'candyshop-e1a60',
    authDomain: 'candyshop-e1a60.firebaseapp.com',
    storageBucket: 'candyshop-e1a60.appspot.com',
    measurementId: 'G-998GQ4TP4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1vuKXknXcu-RAFpSJH6p5XZXZnk9_QQ',
    appId: '1:482587259419:android:df177310496c47cef73ebe',
    messagingSenderId: '482587259419',
    projectId: 'candyshop-e1a60',
    storageBucket: 'candyshop-e1a60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfMUzE23H3GvVJWTS-ASwOe7gyDLvXT0',
    appId: '1:482587259419:ios:642c746fb424aef4f73ebe',
    messagingSenderId: '482587259419',
    projectId: 'candyshop-e1a60',
    storageBucket: 'candyshop-e1a60.appspot.com',
    iosClientId: '482587259419-fpgo2o75c61smiqj9mmnhacmejao41ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.candyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfMUzE23H3GvVJWTS-ASwOe7gyDLvXT0',
    appId: '1:482587259419:ios:642c746fb424aef4f73ebe',
    messagingSenderId: '482587259419',
    projectId: 'candyshop-e1a60',
    storageBucket: 'candyshop-e1a60.appspot.com',
    iosClientId: '482587259419-fpgo2o75c61smiqj9mmnhacmejao41ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.candyShop',
  );
}
